export const en = {
    translation: {
        actions: {
            confirm: "Confirm",
            workspace: {
                create: "Create work space",
            },
        },
        inputs: {
            folders: {
                empty: "Drag and drop you folder here",
                unselected: "Select a file to see his content",
                unsupported: "Type of file not supported. Supported type of files: ",
            },
        },
        home: {
            navigation: {
                buttons: {
                    new: "New preparation",
                    old: "Old preparations",
                    voc: "Generated vocabulary",
                },
            },
            new: {
                title: "Prepare a speech",
                inputs: {
                    "meeting-documents": "Provide the documents related to the reunion that you are preparing.",
                    title: "Define a title for this preparation",
                },
            },
            old: {
                title: "My preparations",
            },
            voc: {
                title: "Vocabulary generated by my preparations",
            },
            workspace: {
                title: "Create a custom work space.",
                inputs: {
                    title: {
                        label: "Define a title for your work space.",
                        errorMessages: {
                            length: "Title length must be between 3 and 45 characters.",
                        },
                    },
                    "work-languages": {
                        label: "Define the languages you are working with.",
                        errorMessages: {
                            length: "Select at least two languages.",
                        },
                    },
                    "native-language": {
                        label: "Pick one of those to define your native language.",
                    },
                },
            },
        },
    },
};
