export const en = {
    translation: {
        actions: {
            add: "Add",
            confirm: "Confirm",
            workspace: {
                create: "Create work space",
            },
        },
        colorPanel: {
            creation: {
                action: "Create a color panel",
                title: "Color panel creation"
            },
            colors: {
                label: "Define the colors",
                placeholder: "Sources",
            },
            displayer: {
                color: "COLOR",
                name: "NAME",
            },
            title: {
                label: "Define a title",
                placeholder: "Default color panel",
            },
            missing: "No color panel found"
        },
        files: {
            "context-menu": {
                delete: "Delete the file",
                rename: "Rename the file",
            },
            editor: {
                "context-menu": {
                    highlight: "Highlight the selection",
                    note: "Create a note from selection",
                    underline: "Underline the selection",
                    vocabulary: "Add to vocabulary",
                },
                tools: {
                    backward: "Backward",
                    brush: "Brush",
                    close: "Close",
                    color: "Change color",
                    drag: "Drag",
                    forward: "Forward",
                    highlight: "Highlight",
                    horizontal: "Horizontal display",
                    note: "Add a note",
                    open: "Open",
                    underline: "Underline",
                    vertical: "Vertical display",
                    vocabulary: "Add to vocabulary",
                }
            }
        },
        inputs: {
            folders: {
                empty: "Drag and drop you folder here",
                unselected: "Select a file to see his content",
                unsupported: "Type of file not supported. Supported type of files: ",
            },
            notRequired: "Not required",
        },
        navigation: {
            buttons: {
                dictionary: "Dictionary",
                files: "Source folders",
                home: "My work space",
                preparations: "Old preparations",
                prepare: "New preparation",
                vocabulary: "Vocabulary",
            },
        },
        notes: {
            add: "Add a note",
            navigate: "Navigate to note",
            placeholder: "Fill the note",
        },
        views: {
            home: {
                title: "My work space",
                sections: {
                    languages: "Languages",
                    colorPanel: "Color panel",
                },
            },
            new: {
                "context-menu": {
                    folder: {
                        create: "Create new folder",
                        delete: "Delete the folder",
                        rename: "Rename the folder",
                    },
                },
                inputs: {
                    "meeting-documents": "Provide the documents related to the reunion that you are preparing.",
                    title: "Define a title for this preparation",
                },
                title: "Prepare a speech",
            },
            notFound: {
                title: "Oops, someone got lost?",
                buttonLabel: "Back to safety"
            },
            old: {
                title: "My preparations",
            },
            dic: {
                title: "Vocabulary generated by my preparations",
            },
            workspace: {
                title: "Create a custom work space.",
                inputs: {
                    title: {
                        label: "Define a title for your work space.",
                        errorMessages: {
                            length: "Title length must be between 3 and 45 characters.",
                        },
                    },
                    "work-languages": {
                        label: "Define the languages you are working with.",
                        errorMessages: {
                            length: "Select at least two languages.",
                        },
                    },
                    "native-language": {
                        label: "Pick one of those to define your native language.",
                    },
                },
            },
        },
        vocabulary: {
            empty: "No vocabulary generated yet",
            placeholder: "Translate {{ word }} ({{ language }})",
            sources: "Sources",
        },
    },
};
