const deeplLanguageMap: Record<string, string> = {
	ar: "AR",
	bg: "BG",
	cs: "CS",
	da: "DA",
	de: "DE",
	el: "EL",
	en: "EN",
	es: "ES",
	et: "ET",
	fi: "FI",
	fr: "FR",
	hu: "HU",
	id: "ID",
	it: "IT",
	ja: "JA",
	ko: "KO",
	lt: "LT",
	lv: "LV",
	nb: "NB",
	nl: "NL",
	pl: "PL",
	pt: "PT",
	ro: "RO",
	ru: "RU",
	sk: "SK",
	sl: "SL",
	sv: "SV",
	tr: "TR",
	uk: "UK",
	zh: "ZH",
};
export const toDeepLanguage = (locale: string) => deeplLanguageMap[locale.trim().toLowerCase()];
export const toLocale = (language: string) => language.trim().toLowerCase();
